db_proj4/Controllers/ApplicantsController.cs
using System;
using System.Collections.Generic;
using System.Data.Common;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using System.Web.Security;
using db_proj4.Models;
using db_proj4.Models.entities;
using Microsoft.Practices.EnterpriseLibrary.Data;

namespace db_proj4.Controllers
{
    public class ApplicantsController : Controller
    {
        ApplicantsRepository appRepo = new ApplicantsRepository();
        // appRepo = new ApplicantsRepository();

        public ActionResult Create(int Id)
        {
            ViewData["Userid"] = Id;
            return View();
        }


        [HttpPost]
        public ActionResult Create(Applicants app)
        {
            ApplicantsRepository.InsertApplicant(app.Userid, app.Fname, app.Lname, app.School, app.Aemail,
                app.Degree, app.DegreeField);
            return RedirectToAction("LogOn", "Account");
        }

        public ActionResult Edit(int id)
        {
            var model = appRepo.ViewEditApplicant(id);
            return View(model);
        }
        [HttpPost]
        public ActionResult Edit(Applicants app)
        {

            int Userid = app.Userid;
            string Fname = app.Fname, Lname = app.Lname, School = app.School, Aemail = app.Aemail,
                   Degree = app.Degree, DegreeField = app.DegreeField;

            ApplicantsRepository.UpdateApplicant(Userid, Fname, Lname, School, Aemail, Degree, DegreeField);

            return RedirectToAction("Index", "Jobs");
        }



        public ActionResult Pro()
        {
            string name = User.Identity.Name;
            var modelUser = appRepo.FindUserid(name);
            var model = appRepo.ViewEditApplicant(modelUser.Userid);
            return View(model);


        }

        [HttpPost]
        public ActionResult Pro(Applicants app)
        {
            Database db = DatabaseFactory.CreateDatabase();

            DbCommand command = db.GetStoredProcCommand("Applicant_Update");

            db.AddInParameter(command, "@Appid", System.Data.DbType.Int32, 2);
            db.AddInParameter(command, "@Userid", System.Data.DbType.Int32, 1);
            db.AddInParameter(command, "@Fname", System.Data.DbType.String, app.Fname);
            db.AddInParameter(command, "@Lname", System.Data.DbType.String, app.Lname);
            db.AddInParameter(command, "@School", System.Data.DbType.String, app.School);
            db.AddInParameter(command, "@Aemail", System.Data.DbType.String, app.Aemail);
            db.AddInParameter(command, "@Degree", System.Data.DbType.String, app.Degree);
            db.AddInParameter(command, "@DegreeField", System.Data.DbType.String, app.DegreeField);

            db.ExecuteScalar(command);

            return RedirectToAction("Index", "Jobs");
        }

        public ActionResult Delete(int id)
        {
            Database db = DatabaseFactory.CreateDatabase();

            DbCommand command = db.GetStoredProcCommand("Applicants_DeleteApplicant");
            string name = User.Identity.Name;
            var modelUser = appRepo.FindUserid(name);
            var modelUserAppid = appRepo.FindAppid(modelUser.Userid);
            db.AddInParameter(command, "@Appid", System.Data.DbType.Int32, modelUserAppid.Appid);
            db.AddInParameter(command, "@Userid", System.Data.DbType.Int32, id);
            db.ExecuteScalar(command);

            return RedirectToAction("Index", "Jobs");
        }
    }
}

db_proj4/Controllers/RecruitersController.cs
using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using System.Web.Security;
using db_proj4.Models;
using db_proj4.Models.entities;
using Microsoft.Practices.EnterpriseLibrary.Data;

namespace db_proj4.Controllers
{
    public class RecruitersController : Controller
    {
        RecruitersRepository recRepo = new RecruitersRepository();

        public ActionResult Create(int Id)
        {
            ViewData["Userid"] = Id;
            return View();
        }


        [HttpPost]
        public ActionResult Create(Recruiters rec)
        {
            RecruitersRepository.InsertRecruiter(rec.Userid, rec.Company, rec.Focus, rec.Remail);
            return RedirectToAction("LogOn", "Account");
        }

        public ActionResult Edit(int id)
        {
            var model = recRepo.ViewEditRecruiter(id);
            return View(model);
        }
        [HttpPost]
        public ActionResult Edit(Recruiters rec)
        {
            int Userid = rec.Userid;
            string Company = rec.Company, Focus = rec.Focus, Remail = rec.Remail;

            RecruitersRepository.UpdateRecruiter(Userid, Company, Focus, Remail);

            return RedirectToAction("Index", "Jobs");
        }

        public ActionResult Pro()
        {
            string name = User.Identity.Name;
            var modelUser = recRepo.FindUserid(name);
            var model = recRepo.ViewEditRecruiter(modelUser.Userid);
            return View(model);


        }

        public ActionResult Delete(int id)
        {
            Database db = DatabaseFactory.CreateDatabase();

            DbCommand command = db.GetStoredProcCommand("Recruiters_DeleteRecruiter");
            string name = User.Identity.Name;
            var modelUser = recRepo.FindUserid(name);
            var modelUserRid = recRepo.FindRid(modelUser.Userid);
            db.AddInParameter(command, "@Rid", System.Data.DbType.Int32, modelUserRid.Rid);
            db.AddInParameter(command, "@Userid", System.Data.DbType.Int32, id);
            db.ExecuteScalar(command);

            return RedirectToAction("Index", "Jobs");
        }
    }
}

db_proj4/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.7.1.min.js")" type="text/javascript"></script>
</head>
<body>
    <div class="page">
        <div id="header">
            <div id="title">
                <h1>Job Loader</h1>
            </div>
            <div id="logindisplay">
                @Html.Partial("_LogOnPartial")
            </div>
            <div id="menucontainer">
                <ul id="menu">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    @if (Request.IsAuthenticated)
                    { 
                         @if (db_proj4.Models.JobsRepository.GetType(User.Identity.Name).Equals("Recruiter"))
                         {
                             <li>@Html.ActionLink("Profile", "Pro", "Recruiters")</li> 
                         }
                         else
                         {
                             <li>@Html.ActionLink("Profile", "Pro", "Applicants")</li>
                         }
                        <li>@Html.ActionLink("Jobs", "Index", "Jobs")</li> 
                    }
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                </ul>
            </div>
        </div>
        
                 <div id="main">
                @RenderBody()
            </div>
        
        <div id="footer">
        </div>
    </div>
</body>
</html>

db_proj4/Views/Shared/_LogOnPartial.cshtml
@if(Request.IsAuthenticated) {
    <text>Welcome <strong>@User.Identity.Name</strong>!
    [ @Html.ActionLink("Log Off", "LogOff", "Account") ]</text>
}
else {
    @:[ @Html.ActionLink("Log On", "LogOn", "Account") ]
}